#!/usr/bin/env zsh

# SSH with screen session
# Usage: sshs <host> [session_name]
# Example: sshs local@ph02-ansible-02.scv.apple.com
# Example: sshs local@ph02-ansible-02.scv.apple.com mysession

function sshs() {
    local host="$1"
    local session_name="${2:-$(whoami)}"

    if [[ -z "$host" ]]; then
        echo "Usage: sshs <host> [session_name]"
        echo "Example: sshs local@ph02-ansible-02.scv.apple.com"
        echo "Example: sshs local@ph02-ansible-02.scv.apple.com mysession"
        return 1
    fi

    ssh -t "$host" "screen -S '$session_name'"
}

sshs "$@"